# Generated by Django 5.2.3 on 2025-06-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiniShopApp', '0003_alter_purchase_added_by_alter_sale_added_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=5, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=5, editable=False, max_digits=10),
            preserve_default=False,
        ),
    ]
