# Generated by Django 5.2.3 on 2025-06-22 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiniShopApp', '0004_purchase_total_price_sale_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='added_by',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='added_by',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='added_by',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='added_by',
            new_name='owner',
        ),
    ]
